project:
  type: website
  output-dir: docs

website:
  title: "Jim Teal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: CV.qmd
        text: CV
      

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true
    page-layout: full



