---
toc: false
about:
  template: marquee
---


# Publications

------

* Stevens, A.W., **J. Teal**, C. D. Court, G. DiGiacomo, M. Miller & H. H. Peterson (2024). [Predicting Firm Diversification in Agri-Food Value Chains](https://www.fdrsinc.org/wp-content/uploads/2024/12/JFDR55.3_3_Stevens.pdf). *Journal of Food Distribution Research*, 55(3), 43-64.

* **Teal, J.** & A. W. Stevens (2024). [Race and premium misrating in the U.S. Federal Crop Insurance Program](https://onlinelibrary.wiley.com/doi/full/10.1002/aepp.13397). *Applied Economic Perspectives and Policy*, 46(1), 169-188.

* Stevens, A. W. & **J. Teal** (2024). [Diversification and resilience of firms in the agrifood supply chain](https://onlinelibrary.wiley.com/doi/10.1111/ajae.12398). *American Journal of Agricultural Economics*, 106(2), 739-778.

# Working Papers

----

* **Teal, J.**, ["Crop Diversification and Farm Resilience: An Entropy-Based Evaluation of Agricultural Lending Performance"](WorkingPapers/WorkingPaper_DiversityLoanRisk.pdf) [Job Market Paper]

  Agricultural producers have greatly benefited from the economies of scale in agriculture. By taking advantage of these economies of scale, producers choose to specialize in only a small number of crops. Although specialization has the benefits of higher expected returns, there is a trade-off with increased risk exposure. Consequently, increases in large scale specialization have increased risk for agricultural lenders. This is especially true for regional banks which may only lend to producers in a small number of neighboring counties. I evaluate whether declines in crop diversification have negatively impacted agricultural loan performance and if certain types of diversification have less of an impact than other types. I show that diversification does have an impact on delinquency rates of agricultural loans. Contrary to conventional wisdom, diversification increases delinquency rates for agricultural production loans and real estate loans secured by farmland. A one standard deviation increase in a lender’s diversification exposure raises production loan delinquencies by over 13% and real estate loan delinquencies by 11%. The negative impact of diversification on real estate loans is primarily driven by diversification “within similar” crop groups. My results suggest that not all diversification is created equally, and some forms of diversification are actually risk increasing instead of risk mitigating.

# Works In Progress

----

* **Teal, J.**, "Measurement Differences in Agricultural Diversification"

  How do measures of agricultural diversification differ across different data sources of land cover? This research highlights how different data sources are not interchangeable and which data sources are best for certain types of projects. Primary diversification indexes are calculated using the Cropland Data Layer (CDL) and the Farm Service Agency (FSA) Crop Acreage Data, from 2009 to 2018. When selecting on highly productive counties and crops, CDL and FSA diversification are highly similar with a correlation coefficient of 0.82. When comparing county-year pairs across the entire data set, differences become more extreme with a lower correlation coefficient of 0.52. Differences also exhibit a non-random behavior violating classical measurement error. As CDL diversification increases, CDL diversification becomes increasingly more diversified than FSA.


* **Teal, J.**, "Downstream Intensification and Local Landscape Diversification:
How Increased Demand for Agricultural Inputs Changes Local Landscapes"

  How agricultural products are used has an impact on the intensity a crop is grown. The U.S. Renewable Fuel Standard greatly increased corn acreage. Similarly in the coming years, as the demand for biodiesel increases, soybean acreage will need to increase to match that demand. With growing urban pressure on farmlands and the current level of agricultural intensification in the United States, additional soybean acreage is likely to be substituted from other crops to soybeans instead of new farm acres being planted. How does the increased demand for an agricultural input change local landscape diversification? I answer this question using the introduction of soybean crush plants; ethanol refineries; meat, poultry and egg slaughter facilities; and local landcover from the Cropland Data Layer. When soybean crush plants; ethanol refineries; and meat, poultry and egg slaughter facilities enter an area, there is an increased demand for local agricultural inputs to supply these facilities. I take advantage of this variation to determine if local landscape diversification changes, or if these plants choose to open in locations with excess supply of the needed inputs.


























