---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=15mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage[T1]{fontenc}
        \usepackage{charter}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- fontfamily: libertinus -->
<!-- TITLE -->
\begin{huge}
  \begin{center}{\textbf{\sc{Jim Teal}}}\end{center}
\end{huge}
\vspace{3pt}
\begin{large}
  \begin{multicols}{3}
  \end{multicols}
\end{large}
\vspace{3pt}
\hrule
\vspace{3pt}

<!-- Department and Contact Info -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}
       University of Wisconsin--Madison\\
       Agricultural \& Applied Economics\\
       \textit{Ph.D. Candidate}\\
       ~\\
       ~\\
    \end{flushleft}
    \begin{flushright}
       427 Lorch St.\\
       Madison, WI 53706\\
       (931) 581-8563\\
       \href{mailto:jteal@wisc.edu}{JTeal@wisc.edu}\\
       \href{https://JTealAgEconomist.github.io}{JTealAgEconomist.github.io}
    \end{flushright}
  \end{multicols}
\end{large}

<!-- EDUCATION -->
\begin{large}
  {\textbf {EDUCATION}}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\begin{normalsize}
  \textbf{University of Wisconsin--Madison}
  \begin{multicols}{2}
    \begin{flushleft}Ph.D., Agricultural and Applied Economics\end{flushleft}
    \begin{flushright}Expected May 2026\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \hspace*{0.5 cm}Primary Field: Agricultural Economics\\
  \hspace*{0.5 cm}Secondary Field: Industrial Organization\\
  \hspace*{0.5 cm}Dissertation:
  \textit{Three Essays on Agricultural Diversification}\\
  \hspace*{0.5 cm}Committee: Paul Mitchell, Guanming Shi, and Andrew Stevens (Chair)
  \vspace{0.15cm}
\end{normalsize}

\begin{normalsize}
  \textbf{University of California--Davis}
  \begin{multicols}{2}
    \begin{flushleft}M.Sc., Agricultural and Resource Economics\end{flushleft}
    \begin{flushright}2019\end{flushright}
  \end{multicols}
  \vspace{0.15cm}
\end{normalsize}


\begin{normalsize}
  \textbf{University of Tennessee--Knoxville}
  \begin{multicols}{2}
    \begin{flushleft}B.A., Economics\end{flushleft}
    \begin{flushright}2015\end{flushright}
  \end{multicols}
  \vspace{0.15cm}
\end{normalsize}

<!-- Published Research -->
\begin{large}
  \textbf {PUBLICATIONS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

Stevens, A. W., \textbf{J. Teal}, C. D. Court, G. DiGiacomo, M. Miller
\& H. H. Peterson (2024).
\href{https://www.fdrsinc.org/wp-content/uploads/2024/12/JFDR55.3_3_Stevens.pdf}{Predicting Firm Diversification in Agri-Food Value Chains}.
\textit{Journal of Food Distribution Research}, 55(3), 43-64.

\vspace{5pt}

\textbf{Teal, J.} \& A. W. Stevens (2024).
\href{https://onlinelibrary.wiley.com/doi/full/10.1002/aepp.13397}{Race and Premium Misrating in the U.S. Federal Crop Insurance Program}.
\textit{Applied Economic Perspectives and Policy}, 46(1), 169-188.

\vspace{5pt}

Stevens, A. W. \& \textbf{J. Teal} (2024). 
\href{https://onlinelibrary.wiley.com/doi/10.1111/ajae.12398}{Diversification and Resilience of Firms in the Agrifood Supply Chain}.
\textit{American Journal of Agricultural Economics}, 106(2), 739-778.

\vspace{7pt}

<!-- Working Papers -->
\begin{large}
  \textbf {WORKING PAPERS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\textbf{Teal, J.}, 
"Crop Diversification and Banking Resilience: An Entropy-Based Evaluation of 
Agricultural Lending Performance." [Job Market Paper]

>Does agricultural diversification exposure of lending institutions decrease agricultural loan delinquency rates, and does the type of diversification matter? Using call reports from the Federal Deposit Insurance Corporation and planted acreage reports from the Farm Service Agency, I show that diversification does have an impact on the delinquency rates of agricultural loans. Contrary to the initial hypothesis, diversification increases delinquency rates for agricultural production loans and real estate loans secured by farmland. A one standard deviation increase in diversification exposure would raise production loan delinquencies by over 13% and real estate loan delinquencies by 11%. To determine if the type of diversification matters, I calculate diversification using the Shannon Entropy Index which can be separated into between group and within group diversification. The impact of different types of diversification on delinquency rates is highly context specific. Within group diversification has a larger negative impact than general diversification on real estate loans. For production loans, there is no difference between the different types of diversification. My results suggest that, in some situations, all diversification is not created equally, and some forms of diversification are actually risk increasing instead of risk mitigating.

\vspace{7pt}

\pagebreak

<!-- Works in Progress -->
\begin{large}
  \textbf {WORKS IN PROGRESS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\textbf{Teal, J.}, 
"Measurement Differences in Agricultural Diversification."

>How do measures of agricultural diversification differ across different data sources of land cover? This research highlights how different data sources are not interchangeable and which data sources are best for certain types of projects. Primary diversification indexes are calculated using the Cropland Data Layer (CDL) and the Farm Service Agency (FSA) Crop Acreage Data, from 2009 to 2018. When selecting on highly productive counties and crops, CDL and FSA diversification are highly similar with a correlation coefficient of 0.82. When comparing county-year pairs across the entire data set, differences become more extreme with a lower correlation coefficient of 0.52. Differences also exhibit a non-random behavior violating classical measurement error. As CDL diversification increases, CDL diversification becomes increasingly more diversified than FSA.

\textbf{Teal, J.},
"Downstream Intensification and Local Landscape Diversification:
How Increased Demand for Agricultural Inputs Changes Local Landscapes"

>How agricultural products are used has an impact on the intensity a crop is grown. The U.S. Renewable Fuel Standard greatly increased corn acreage. Similarly in the coming years, as the demand for biodiesel increases, soybean acreage will need to increase to match that demand. With growing urban pressure on farmlands and the current level of agricultural intensification in the United States, additional soybean acreage is likely to be substituted from other crops to soybeans instead of new farm acres being planted. How does the increased demand for an agricultural input change local landscape diversification? I answer this question using the introduction of soybean crush plants; ethanol refineries; meat, poultry and egg slaughter facilities; and local landcover from the Cropland Data Layer. When soybean crush plants; ethanol refineries; and meat, poultry and egg slaughter facilities enter an area, there is an increased demand for local agricultural inputs to supply these facilities. I take advantage of this variation to determine if local landscape diversification changes, or if these plants choose to open in locations with excess supply of the needed inputs.

\vspace{7pt}

<!-- Employment -->
\begin{large}
  \textbf {RESEARCH \& PROFESSIONAL EXPERIENCE}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\begin{normalsize}
  \begin{flushleft}{\textbf {University of Wisconsin--Madison}}\end{flushleft}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Research Assistant}}\end{flushleft}
    \begin{flushright}September 2020--Present\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \hspace*{0.5 cm}Supervisor: Dr. Andrew Stevens
\end{normalsize}

\begin{normalsize}
  \begin{flushleft}{\textbf {United States Department of Agriculture}}\end{flushleft}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Economic Research Service Pathways Intern}}\end{flushleft}
    \begin{flushright}Summer 2022\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \hspace*{0.5 cm}Supervisor: Dr. Michael Ollinger
\end{normalsize}

\begin{normalsize}
  \begin{flushleft}{\textbf {Conservation Strategy Fund}}\end{flushleft}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Research Associate}}\end{flushleft}
    \begin{flushright}November 2019--September 2020\end{flushright}
  \end{multicols}
\end{normalsize}

\begin{normalsize}
  \begin{flushleft}{\textbf {Federal Reserve Board of Governors}}\end{flushleft}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Senior Research Assistant}}\end{flushleft}
    \begin{flushright}July 2017--July 2018\end{flushright}
  \end{multicols}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Research Assistant}}\end{flushleft}
    \begin{flushright}January 2016--June 2017\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \hspace*{0.5 cm}Supervisor: Dr. Gustavo Suarez \& Dr. Nitish Sinha
\end{normalsize}

\begin{normalsize}
  \begin{flushleft}{\textbf {University of Tennessee--Knoxville}}\end{flushleft}
  \vspace{-0.10cm}
  \begin{multicols}{2}
    \begin{flushleft}{\hspace*{0.5cm}\textit{Research Assistant}}\end{flushleft}
    \begin{flushright}Summer 2022\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
  \hspace*{0.5 cm}Supervisor: Dr. Marianne Wanamaker
\end{normalsize}

\vspace{7pt}

<!-- Teaching -->
\begin{large}
  \textbf {TEACHING EXPERIENCE}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}


\begin{normalsize}
  \textbf{University of Wisconsin--Madison}\\
  \vspace{-0.10cm}
  AAE 421: Economic Decision Analysis
  \begin{multicols}{2}
    \begin{flushleft}{
    \hspace*{0.5 cm}\textit{Teaching Assistant}
    }\end{flushleft}
    \begin{flushright}{Fall 2023 \& Fall 2024}\end{flushright}
  \end{multicols}
\end{normalsize}
\vspace{-0.25cm}
* Co-developed, implemented, and improved through iteration a
  course lab project analyzing data from a hypothetical on-farm precision experiment
* Overall performance rating from student evaluations 4.15 and 4.45 out of 5

\pagebreak

\begin{normalsize}
  \textbf{University of California--Davis}\\
  \vspace{-0.10cm}
  ARE 100B: Intermediate Microeconomics
  \begin{multicols}{2}
    \begin{flushleft}{
    \hspace*{0.5 cm}\textit{Reader}\\
    \hspace*{0.5 cm}\textit{Teaching Assistant}\\
    }\end{flushleft}
    \begin{flushright}{ 
    Spring 2019\\
    Winter 2019}\end{flushright}
  \end{multicols}
\end{normalsize}
\vspace{-0.25cm}
* Overall effectiveness rating from student evaluations 4.7 out of 5

\vspace{7pt}

<!-- Presentations -->

\begin{large}
  \textbf {PRESENTATIONS}
  \vspace{3pt}
  \hrule
\end{large} 

\vspace{3pt}
  2025 - 
SCC-76: Economics and Management of Risk in Agriculture and Natural
Resources Annual Meeting (Kansas City, MO).

\vspace{3pt}
  2024 -
American Society of Farm Managers and Rural Appraisers Wisconsin Chapter 
(Prairie du Sac, WI),
Agricultural and Applied Economics Association (AAEA) Annual Meeting 
(New Orleans, LA), 
NC-1177: Agricultural and Rural Finance Markets in
Transition Annual Meeting (St. Louis, MO)

\vspace{3pt}
  2023 - 
United States Department of Agriculture Economic Research Services
(Kansas City, MO)

\vspace{3pt}
  2022 - 
NC-1177: Agricultural and Rural Finance Markets in Transition Annual Meeting 
(Detroit, MI)

\vspace{7pt}

<!-- Fellowships, Honors and Awards -->
\begin{large}
  \textbf {FELLOWSHIPS, HONORS, AND AWARDS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{Graduate Student Travel Award (\$500)}
    \end{flushleft}
    \begin{flushright}2025\end{flushright}
  \end{multicols}
    \vspace{-0.25cm}
    \hspace*{0.5 cm}Applied Risk Analysis AAEA Section
\end{normalsize}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{Graduate Student Travel Award (\$500)}
    \end{flushleft}
    \begin{flushright}2025\end{flushright}
  \end{multicols}
    \vspace{-0.25cm}
    \hspace*{0.5 cm}Agricultural Finance \& Management AAEA Section
\end{normalsize}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{Student Research Grants Competition (\$1,500)}
    \end{flushleft}
    \begin{flushright}2024\end{flushright}
  \end{multicols}
    \vspace{-0.25cm}
    \hspace*{0.5 cm}University of Wisconsin--Madison
\end{normalsize}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{Mueller Fellowship Recipient}\end{flushleft}
    \begin{flushright}2024\end{flushright}
  \end{multicols}
\end{normalsize}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{Farm Foundation Agricultural Scholar}\end{flushleft}
    \begin{flushright}2023\end{flushright}
  \end{multicols}
\end{normalsize}


\vspace{7pt}

<!-- Service -->
\begin{large}
  \textbf {SERVICE}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\begin{multicols}{2}
  \begin{flushleft}{Graduate student representative for Ph.D. admissions}\end{flushleft}
  \begin{flushright}2024--2025\end{flushright}
\end{multicols}

\begin{multicols}{2}
  \begin{flushleft}{UW AAE graduate committee representitive}\end{flushleft}
  \begin{flushright}2024--2025\end{flushright}
\end{multicols}

\begin{multicols}{2}
  \begin{flushleft}{Abstract reviewer for AAEA}\end{flushleft}
  \begin{flushright}2024\end{flushright}
\end{multicols}

\begin{normalsize}
  \begin{multicols}{2}
    \begin{flushleft}{President of the Taylor-Hibbard Club}\end{flushleft}
    \begin{flushright}September 2021--July 2023\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \hspace*{0.5cm}UW AAE graduate student organization
\end{normalsize}

\begin{multicols}{2}
  \begin{flushleft}{Referee for \textit{Applied Economic Perspectives and Policy}}\end{flushleft}
  \begin{flushright}2022\end{flushright}
\end{multicols}

\vspace{7pt}

<!-- Professional Affiliations -->
\begin{large}
  \textbf {PROFESSIONAL AFFILIATIONS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}
Agricultural \& Applied Economics Association

\vspace{7pt}

<!-- Skills -->
\begin{large}
  \textbf {SKILLS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

Proficient in R, LaTeX, Markdown, data visualization, and Linux-based operating
systems\newline
Experience in MATLAB, SQL, ArcGIS, SAS, and STATA\newline
Regular use of the Tidyverse libraries within R including dplyr, purrr, and
ggplot2\newline

\vspace{7pt}

<!-- References -->
\begin{large}
  \textbf {REFERENCES}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
\end{large}

\begin{multicols}{3}
  \begin{flushleft}
  \textbf{Andrew Stevens}\\
  Assistant Professor\\
  Agricultural \& Applied Economics\\
  University of Wisconsin--Madison\\
  e-mail: \href{mailto:AWStevens@wisc.edu}{AWStevens@wisc.edu}\\
  phone: (608) 263-3212\\
  ~\\
  \textbf{Paul Mitchell}\\
  Professor \& Department Chair\\
  Agricultural \& Applied Economics\\
  University of Wisconsin--Madison\\
  e-mail: \href{mailto:PDMitchell@wisc.edu}{PDMitchell@wisc.edu}\\
  phone: (608) 265-6514\\
  ~\\
  \textbf{Guanming Shi}\\
  Renk Agribusiness Chair \& Professor\\
  Agricultural \& Applied Economics\\
  University of Wisconsin--Madison\\
  e-mail: \href{mailto:gshi@wisc.edu}{GShi@wisc.edu}\\
  phone: (608) 262-8966\\
  \end{flushleft}
\end{multicols}
























